export default [
    {
        "color-scheme": "dark",
        "primary": "#09ecf3",
        "primary-content": "#005355",
        "secondary": "#0966fb3",
        "accent": "#ffe999",
        "neutral": "#3b8ac4",
        "base-100": "#345da7",
        "info": "#2563eb",
        "success": "#16a34a",
        "warning": "#d97706",
        "error": "oklch(73.95% 0.19 27.33)",
        "theme": "aqua"
    },
    {
        "color-scheme": "light",
        "primary": "#3b82f6",
        "primary-content": "#ffffff",
        "secondary": "#ec4899",
        "accent": "#22c55e",
        "neutral": "#64748b",
        "base-100": "#f3f4f6",
        "info": "#0ea5e9",
        "success": "#10b981",
        "warning": "#f59e0b",
        "error": "#ef4444",
        "theme": "light"
    },
    {
        "color-scheme": "cupcake",
        "primary": "#65c3c8",
        "primary-content": "#ffffff",
        "secondary": "#ef9fbc",
        "accent": "#eeaf3a",
        "neutral": "#291334",
        "base-100": "#faf7f5",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "cupcake"
    },
    {
        "color-scheme": "bumblebee",
        "primary": "#e0a82e",
        "primary-content": "#ffffff",
        "secondary": "#f9d72f",
        "accent": "#181830",
        "neutral": "#181830",
        "base-100": "#ffffff",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "bumblebee"
    },
    {
        "color-scheme": "emerald",
        "primary": "#66cc8a",
        "primary-content": "#ffffff",
        "secondary": "#377cfb",
        "accent": "#ea5234",
        "neutral": "#333c4d",
        "base-100": "#ffffff",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "emerald"
    },
    {
        "color-scheme": "corporate",
        "primary": "#4b6bfb",
        "primary-content": "#ffffff",
        "secondary": "#7b92b2",
        "accent": "#67cba0",
        "neutral": "#181a2a",
        "base-100": "#ffffff",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "corporate"
    },
    {
        "color-scheme": "synthwave",
        "primary": "#e779c1",
        "primary-content": "#ffffff",
        "secondary": "#58c7f3",
        "accent": "#f3cc30",
        "neutral": "#20134e",
        "base-100": "#2d1b69",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "synthwave"
    },
    {
        "color-scheme": "retro",
        "primary": "#ef9995",
        "primary-content": "#282425",
        "secondary": "#a4cbb4",
        "accent": "#ebdc99",
        "neutral": "#7d7259",
        "base-100": "#e4d8b4",
        "info": "#2563eb",
        "success": "#16a34a",
        "warning": "#fbbf24",
        "error": "#dc2626",
        "theme": "retro"
    },
    {
        "color-scheme": "valentine",
        "primary": "#e96d7b",
        "primary-content": "#ffffff",
        "secondary": "#a991f7",
        "accent": "#88dbdb",
        "neutral": "#af4670",
        "base-100": "#f7d7db",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "valentine"
    },
    {
        "color-scheme": "halloween",
        "primary": "#f28c18",
        "primary-content": "#ffffff",
        "secondary": "#ff6f00",
        "accent": "#66d9e8",
        "neutral": "#291334",
        "base-100": "#212121",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "halloween"
    }, {
        "color-scheme": "forest",
        "primary": "#1eb854",
        "primary-content": "#ffffff",
        "secondary": "#1fd65f",
        "accent": "#d99330",
        "neutral": "#110e0e",
        "base-100": "#171212",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "forest"
    },
    {
        "color-scheme": "luxury",
        "primary": "#7b80a3",
        "primary-content": "#ffffff",
        "secondary": "#e8d8b5",
        "accent": "#a18f6b",
        "neutral": "#1d2333",
        "base-100": "#030201",
        "info": "#66c8ff",
        "success": "#3ecf8e",
        "warning": "#f9cb42",
        "error": "#ff7a85",
        "theme": "luxury"
    },
    {
        "color-scheme": "autumn",
        "primary": "#d2691e",
        "primary-content": "#ffffff",
        "secondary": "#e25822",
        "accent": "#ffdd67",
        "neutral": "#322810",
        "base-100": "#fdf5dc",
        "info": "#3abff8",
        "success": "#86a873",
        "warning": "#d97706",
        "error": "#b23030",
        "theme": "autumn"
    },
    {
        "color-scheme": "pastel",
        "primary": "#d1c1e0",
        "primary-content": "#19151e",
        "secondary": "#a3dee0",
        "accent": "#ffddd2",
        "neutral": "#7a7a7a",
        "base-100": "#ffffff",
        "info": "#81e4ef",
        "success": "#b6e2d3",
        "warning": "#ffce6e",
        "error": "#f3a9a9",
        "theme": "pastel"
    },
    {
        "color-scheme": "dracula",
        "primary": "#ff79c6",
        "primary-content": "#ffffff",
        "secondary": "#bd93f9",
        "accent": "#8be9fd",
        "neutral": "#44475a",
        "base-100": "#282a36",
        "info": "#6272a4",
        "success": "#50fa7b",
        "warning": "#ffb86c",
        "error": "#ff5555",
        "theme": "dracula"
    },
    {
        "color-scheme": "night",
        "primary": "#38bdf8",
        "primary-content": "#ffffff",
        "secondary": "#7dd3fc",
        "accent": "#14b8a6",
        "neutral": "#1e293b",
        "base-100": "#0f172a",
        "info": "#60a5fa",
        "success": "#4ade80",
        "warning": "#fbbf24",
        "error": "#f87171",
        "theme": "night"
    },
    {
        "color-scheme": "winter",
        "primary": "#006d77",
        "primary-content": "#ffffff",
        "secondary": "#83c5be",
        "accent": "#edf6f9",
        "neutral": "#444",
        "base-100": "#e0fbfc",
        "info": "#3a86ff",
        "success": "#2ec4b6",
        "warning": "#ffba08",
        "error": "#ef233c",
        "theme": "winter"
    },
    {
        "color-scheme": "spring",
        "primary": "#fefae0",
        "primary-content": "#5f370e",
        "secondary": "#d9bf77",
        "accent": "#ffcb77",
        "neutral": "#1b4332",
        "base-100": "#edf6f9",
        "info": "#7fc8f8",
        "success": "#80b918",
        "warning": "#ee9b00",
        "error": "#ca6702",
        "theme": "spring"
    },
    {
        "color-scheme": "lofi",
        "primary": "#808080",
        "primary-content": "#191919",
        "secondary": "#9f9f9f",
        "accent": "#bbbbbb",
        "neutral": "#111111",
        "base-100": "#ffffff",
        "info": "#79c2d0",
        "success": "#94d3ac",
        "warning": "#f4bc59",
        "error": "#e66565",
        "theme": "lofi"
    },
    {
        "color-scheme": "cyberpunk",
        "primary": "#ff7598",
        "primary-content": "#181818",
        "secondary": "#ffdf5f",
        "accent": "#8a9bff",
        "neutral": "#383737",
        "base-100": "#0d0d0d",
        "info": "#66c7ff",
        "success": "#1fbc84",
        "warning": "#ff9800",
        "error": "#ff4949",
        "theme": "cyberpunk"
    }
];
